#GENERAL
n_wh: 3 
iterations: 100
i: 100 #iterations in method
batch: 'parameters3'
output: 'Log' #ending of output file structure : {method}{ending}.json
pPath: './build/kCenterProblem ' 
#INPUT
input:
  start: 60
  end: 200
  shift: 10
  baseFile: './input/citiesTest6Csv.json'
#METHODS
bruteForce: true
bruteForceLogIteraions: 'false'
hillClimb: 
  logIterations: 'false'
  deterministic:
    i: 1
  stochastic:
    i: 1
  annealing:
    i: 30
    t: 4000
    t_s: 4000
tabuSearch:
  logIterations: 'false'
  i: 30
  t: 50
  t_s: 50
  