#GENERAL
n_wh: 5
iterations: 10
i: 1000 #iterations in method
batch: 'probTestGa'
output: 'TESTLog' #ending of output file structure : {method}{ending}.json
pPath: './build/kCenterProblem ' 
visualization: 'false'  #generate log for kibana maps
#INPUT
input:
  start: 200
  end: 201
  shift: 10
  baseFile: './input/citiesTest6Csv.json'
#METHODS
bruteForce: false
bruteForceLogIteraions: 'false'
hillClimb: 
  logIterations: 'false'
  deterministic:
    i: 0
  stochastic:
    i: 0
  annealing:
    i: 0
    t: 4000
    t_s: 4000
tabuSearch:
  logIterations: 'false'
  i: 0
  t: 50
  t_s: 50
geneticAlgorithm:
  logIterations: 'false'  #ifset to true can  cause great amout of log data
  probabilityExperiment: 'true'  #if true check all probability properties from 0-1 0.1 shift
  probabilityShift: 0.05  #if true check all probability properties from 0-1 0.1 shift
  i: 1  #every iteraton shifts initPop
  initPop: 100
  initPopShift: 50
  crosProb: 0.9
  crosProbMin: 0.1
  crosProbMax: 1.0
  mutProb: 0.1
  mutProbMin: 0.0
  mutProbMax: 0.9
  #if more than one function every combination of functions will be proceeded
  fitFunc:  
    - 'fitness'
  mutFunc:
    - 'twoPointSwapMutation'
    - 'generateRandomMutation'
  selFunc:
    - 'tournamentSelection'
    - 'rouletteSelection'
  crosFunc:
    - 'twoPointCrossover'
    - 'onePointCrossover'
  termFunc:
    - 'iterationTerminator'
    - 'standardDeviationTerminator'
  
